config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#index"

  resources :players, only: [ :index, :new, :create, :destroy, :show, :edit, :update ]

  resources :characters, only: [ :index, :new, :create, :destroy, :show, :edit, :update ]

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  VALID_CLANS = [ "Banu Haqim", "Brujah", "Gangrel", "Hecata", "Lasombra", "Malkavian", "The Ministry", "Nosferatu", "Ravnos", "Toreador", "Tremere", "Tzimisce", "Ventrue", "Caitiff", "Thin-blood" ]
  belongs_to :player
end

app/models/player.rb
class Player < ApplicationRecord
    validates :name, presence: true, uniqueness: true, length: { minimum: 2 }
    has_many :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end
  def new
    @character = Character.new
  end
def create
  if Player.none?
    redirect_to characters_path, alert: "невозможно создать персонажа, когда не существует игрока."
    return
  end
  @character = Character.new(character_params)
  if @character.save
    redirect_to characters_path
  else
    render :new
  end
end


  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to character_path
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])

    if @character.update(character_params)
      redirect_to character_path(@character)
    end
  end

    def show
      @character = Character.find(params[:id])
    end
end

    private
  def character_params
    params.require(:character).permit(:name, :clan, :generation, :sire,  :player_id)
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    def index
      @players = Player.all
    end
    def new
      @player = Player.new
    end

  def create
    @player = Player.new player_params
    if @player.save
      redirect_to players_path
    else
      render :new
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to players_path
  rescue ActiveRecord::InvalidForeignKey => e
      redirect_to players_path, alert: "У этого игрока есть активные персонажи."
  end
  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    if @player.update(player_params)
      redirect_to player_path(@player)
    end
  end

  def show
    @player = Player.find(params[:id])
  end



    private

  def player_params
    params.require(:player).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/characters/_form.html.erb
<%= form_with model: @character, data: { turbo: false } do |f|%>
<div>
    <%= f.label :name %>
    <%= f.text_field :name, required: true, minlength: 2, placeholder: "Nick Johnsmith" %>
    <%= f.label :clan %><%= f.select :clan, Character::VALID_CLANS, { prompt: "Выберите клан" }, required: true %>
    <%= f.label :sire %>
    <%= f.text_field :sire, required: true, placeholder: "Mr Caine" %>
    <%= f.label :generation %>
    <%= f.text_field :generation, required: true, placeholder: "12" %>
    <%= f.label :player_name %>
    <%= f.collection_select :player_id, Player.all, :id, :name, prompt: "Выберите игрока" %>

</div>
<%= f.submit "Submit character" %>
<%end%> 

app/views/characters/edit.html.erb
<h1>Изменить персонажа</h1>
<%= render 'form' %>

app/views/characters/index.html.erb
<% @characters.each do |character| %>
    <h2><%= character.id%></h2>
    <h2><%= character.name%></h2>
    <%= link_to 'Открыть персонажа', character %>
    <%= form_with url: character_path(character), method: :delete, data: { confirm: 'Точно удалить персонажа?' } do %>
    <%= submit_tag 'Удалить' %>
<% end %>
<% end %>    
<%= link_to 'Добавить персонажа', new_character_path %>
<%= link_to 'К игрокам', players_path %>

app/views/characters/new.html.erb
<h1>Новый персонаж</h1>
<%= render 'form' %>
<%= link_to 'Назад', characters_path %>

app/views/characters/show.html.erb
<h1><%= @character.id %></h1>
<h1><%= @character.name %></h1>
<h1><%= @character.clan %></h1>
<h1><%= @character.generation %></h1>
<h1><%= @character.sire %></h1>
<h1><%= link_to @character.player.name, player_path(@character.player) %></h1>
<%= link_to 'Изменить персонажа', edit_character_path(@character) %>
<%= link_to 'Назад', characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Storyteller Tools Unloaded" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |key, message| %>
    <div class="alert alert-<%= key == "alert" ? "danger" : "success" %>">
      <%= "Невозможно совершить действие: " + message %>
    </div>
<% end %>

  </body>
</html>

app/views/pages/index.html.erb
<h1>Ого</h1>
<%= link_to 'К игрокам', players_path %>
<%= link_to 'К персонажам', characters_path %>

app/views/players/_form.html.erb
<%= form_with model: @player, data: { turbo: false } do |f|%>
<div>
    <%= f.label :name %>
    <%= f.text_field :name, required: true, minlength: 2, placeholder: "Nick Johnsmith" %>
</div>
<%= f.submit "Submit player" %>
<%end%> 

app/views/players/edit.html.erb
<h1>Изменить игрока</h1>
<%= render 'form' %>

app/views/players/index.html.erb
<% @players.each do |player| %>
    <!--<h2><%= player.id%></h2> -->
    <h2><%= player.name%></h2> 
    <%= link_to 'Открыть игрока', player %>
    <%= form_with url: player_path(player), method: :delete, data: { confirm: 'Точно удалить игрока?' } do %>
  <%= submit_tag 'Удалить' %>
<% end %>

<% end %>    
<%= link_to 'Добавить игрока', new_player_path %>
<%= link_to 'К персонажам', characters_path %>

app/views/players/new.html.erb
<h1>Новый игрок</h1>
<%= render 'form' %>
<%= link_to 'Назад', players_path %>

app/views/players/show.html.erb
<!--<h1><%= @player.id %></h1>-->
<h1><%= @player.name %></h1>
<% if @player.characters.any? %>
<ul>
    <% @player.characters.each do |character| %>
     <li>
        <%= link_to character.name, character_path(character) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>У этого игрока пока нет персонажей</p>
<% end %>
<%= link_to 'Изменить игрока', edit_player_path(@player) %>
<%= link_to 'Назад', players_path %>